# Generated by Django 2.1 on 2018-08-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
        ('yazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yazilar', to='kategori.kategori'),
            preserve_default=False,
        ),
    ]
