# Generated by Django 2.1 on 2018-08-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazi', '0002_yazi_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='begeniSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yazi',
            name='goruntulenmeSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
